# meta
lsi: false
safe: false
url: "https://esperanto-societo-de-kioto-universitato.github.io"
source: ./
lang: ja
title:
  ja: 京大エスペラント語研究会
  eo: La Esperanto-Societo de la Universitato de Kioto
description:
  ja: 1919年創立。京都大学でエスペラントを学ぶサークルの公式サイトです。例会案内や活動紹介をお届けします。
  eo: Fondita en 1919. La oficiala retejo de la Esperanto-Societo de la Universitato de Kioto. Ni prezentas niajn agadojn kaj informojn pri la regulaj kunvenoj.
twitter:
  username: esp_univK
  card: summary
timezone: Asia/Tokyo

# social links
twitter_username: esp_univK
instagram_username: esperanto_kyotouniv

incremental: false
highlighter: rouge
permalink: pretty

# defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
header_pages:
  ja:
    - ja/index.md
    - ja/pri-eo.md
    - ja/historio.md
  eo:
    - eo/index.md
    - eo/historio.md
exclude:
  - README.md
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
sass:
  style: compressed
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
